name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run build:preview
      - run: npm test
      - run: npm run lint
      - run: |
          mkdir -p public/integrations/powerbi
          cp dist/upsetjs_venn.pbiviz public/integrations/powerbi/
          cp dist/upsetjs_venn_preview.pbiviz public/integrations/powerbi/
          cp samples/got.pbix public/integrations/powerbi/got_venn.pbix
          cp samples/sample.pbix public/integrations/powerbi/sample_venn.pbix

      - name: Deploy Main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: upsetjs/actions-gh-pages@sgratzl
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          external_repository: upsetjs/upsetjs.github.io
          publish_branch: main
          publish_dir: ./public
          enable_jekyll: true
          keep_files: true

      - if: github.ref == 'refs/heads/dev'
        # move to next directory
        run: |
          mv public public2
          mkdir -p public
          mv public2 public/next

      - name: Deploy Develop
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        uses: upsetjs/actions-gh-pages@sgratzl
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          external_repository: upsetjs/upsetjs.github.io
          publish_branch: main
          publish_dir: ./public
          enable_jekyll: true
          keep_files: true
